version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/auth
  db:
    image: postgres:13.11-bullseye
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth
