version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://auth:auth@db:5432/auth
  db:
    image: postgres:13.11-bullseye
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth
